## Formas de Seleção

In [ ]:
import pandas as pd

In [ ]:
data = [(1, 2, 3, 4),
        (5, 6, 7, 8),
        (9, 10, 11, 12),
        (13, 14, 15, 16)]
df = pd.DataFrame(data, 'l1 l2 l3 l4'.split(), 'c1 c2 c3 c4'.split())
df

    c1  c2  c3  c4
l1   1   2   3   4
l2   5   6   7   8
l3   9  10  11  12
l4  13  14  15  16

In [ ]:
df['c1']

l1     1
l2     5
l3     9
l4    13
Name: c1, dtype: int64

In [ ]:
df[['c3', 'c1']]

    c3  c1
l1   3   1
l2   7   5
l3  11   9
l4  15  13

In [ ]:
df[1:3]

    c1  c2  c3  c4
l2   5   6   7   8
l3   9  10  11  12

In [ ]:
df[1:][['c1','c3']]

    c1  c3
l2   5   7
l3   9  11
l4  13  15

In [ ]:
df.loc['l1']

c1    1
c2    2
c3    3
c4    4
Name: l1, dtype: int64

In [ ]:
df.loc[['l2', 'l3']]

    c1  c2  c3  c4
l2   5   6   7   8
l3   9  10  11  12

In [ ]:
df.loc['l1', 'c2']

2

In [ ]:
df.iloc[0, 1]

2

In [ ]:
df.loc[['l1', 'l3'],['c2', 'c4']]

    c2  c4
l1   2   4
l3  10  12