In [ ]:
import pandas as pd

In [ ]:
data = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
data

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [ ]:
index = list('321')
index

['3', '2', '1']

In [ ]:
df = pd.DataFrame(data, index, list('ZYX'))
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [ ]:
df.sort_index(inplace = True)
df

   Z  Y  X
1  7  8  9
2  4  5  6
3  1  2  3

In [ ]:
df.sort_index(inplace = True, axis = 1)
df

   X  Y  Z
1  9  8  7
2  6  5  4
3  3  2  1

In [ ]:
df.sort_values(inplace = True, by = 'X')
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [ ]:
df.sort_values(inplace = True, by = '3', axis = 1)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9